"""Phase 3 finance, fuel, tasks, and category settings."""
from alembic import op
import sqlalchemy as sa
revision='0003_phase3';down_revision='0002_phase2_resources';branch_labels=None;depends_on=None

def upgrade():
    common=[sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('owner_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False)]
    op.create_table('vehicles',*common,sa.Column('name',sa.String(200),nullable=False),sa.Column('category',sa.String(200),nullable=False),sa.Column('license_plate',sa.String(100)),sa.Column('color',sa.String(100)),sa.Column('details',sa.Text()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index('ix_vehicles_owner_id','vehicles',['owner_id'])
    op.create_table('transactions',*common,sa.Column('type',sa.String(16),nullable=False),sa.Column('category',sa.String(200),nullable=False),sa.Column('item',sa.String(300),nullable=False),sa.Column('amount',sa.Numeric(14,2),nullable=False),sa.Column('date',sa.Date(),nullable=False),sa.Column('cycle_id',sa.Uuid(),sa.ForeignKey('production_cycles.id',ondelete='RESTRICT')),sa.Column('fuel_record_id',sa.Uuid()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.CheckConstraint("type in ('income','expense')",name='transactions_type_valid'),sa.CheckConstraint('amount >= 0',name='transactions_amount_nonnegative'));op.create_index('ix_transactions_owner_id','transactions',['owner_id'])
    op.create_table('fuel_records',*common,sa.Column('vehicle_id',sa.Uuid(),sa.ForeignKey('vehicles.id',ondelete='RESTRICT'),nullable=False),sa.Column('date',sa.Date(),nullable=False),sa.Column('fuel_type',sa.String(100),nullable=False),sa.Column('amount',sa.Numeric(14,2),nullable=False),sa.Column('details',sa.Text()),sa.Column('odometer',sa.Numeric(14,2)),sa.Column('transaction_id',sa.Uuid(),sa.ForeignKey('transactions.id',ondelete='CASCADE'),unique=True),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.CheckConstraint('amount >= 0',name='fuel_amount_nonnegative'),sa.CheckConstraint('odometer is null or odometer >= 0',name='fuel_odometer_nonnegative'));op.create_index('ix_fuel_records_owner_id','fuel_records',['owner_id'])
    op.create_foreign_key('transactions_fuel_record_fk','transactions','fuel_records',['fuel_record_id'],['id'],ondelete='SET NULL')
    op.create_table('tasks',*common,sa.Column('name',sa.String(200),nullable=False),sa.Column('cycle_id',sa.Uuid(),sa.ForeignKey('production_cycles.id',ondelete='RESTRICT'),nullable=False),sa.Column('due_date',sa.Date(),nullable=False),sa.Column('status',sa.String(20),nullable=False),sa.Column('description',sa.Text()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.CheckConstraint("status in ('pending','in_progress','completed')",name='tasks_status_valid'));op.create_index('ix_tasks_owner_id','tasks',['owner_id'])
    op.create_table('category_settings',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('owner_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('key',sa.String(40),nullable=False),sa.Column('values',sa.JSON(),nullable=False),sa.Column('version',sa.Integer(),nullable=False,server_default='1'),sa.UniqueConstraint('owner_id','key',name='uq_category_owner_key'))

def downgrade():
    op.drop_table('category_settings');op.drop_index('ix_tasks_owner_id');op.drop_table('tasks');op.drop_constraint('transactions_fuel_record_fk','transactions',type_='foreignkey');op.drop_index('ix_fuel_records_owner_id');op.drop_table('fuel_records');op.drop_index('ix_transactions_owner_id');op.drop_table('transactions');op.drop_index('ix_vehicles_owner_id');op.drop_table('vehicles')
